name: Lint via ESbuild
on:
  workflow_dispatch:
  push:
jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Initialize Backend
        run: |
          cd apps/backend
          pnpm i --no-frozen-lockfile
          touch node_modules/.modules.yaml

      - name: Version dump
        run: |
          echo Node version:
          node --version
          echo pnpm version:
          pnpm --version
          cd apps/backend/
          pnpm nx report tsn-gql-notework

      # - name: Upload modules.yaml
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: apps/backend/node_modules/.modules.yaml

      - name: Lint Backend
        run: pnpm nx lint tsn-gql-backend

      - name: Initialize Frontend
        run: |
          cd apps/react-tsn
          pnpm i --no-frozen-lockfile
          touch node_modules/.modules.yaml

      - name: Version dump
        run: |
          echo Node version:
          node --version
          echo pnpm version:
          pnpm --version
          cd apps/react-tsn/
          pnpm nx report react-tsn

      - name: Lint Frontend
        run: |
          cd apps/react-tsn/
          pnpm nx lint react-tsn
